### ISSUE TITLE
Formulate our goals for 2016

### ISSUE THREAD

**Issue by effa** [effa/flocs#101]
Suggestions:
* experiments with various recommendation strategies
* interpretable skill, progress and behaviour of the system (incl. statistics)
* our system should be used at some schools
* clean code which is enjoyable to read and write
* master data analysis, student modeling, recommendation strategies, application design, web development, deployment, agile techniques

After we agree on the goals, put them to wiki.

**Comment by xpelanek** [comment]
Don't forget (maybe as a subgoal for  "system should be used at some schools") pragmatic aspects: graphical design, title, story/theme, ... 

I would also recommend more "SMART goals", e.g. to make the usage goal more specific and measurable ("at least 100 visitors per day, used on at least 5 schools, ...").

**Comment by effa** [comment]
Done. See our wiki: https://github.com/effa/flocs/wiki
