### ISSUE TITLE
Check English localization

### ISSUE THREAD

**Issue by effa** [effa/flocs#110]
In particular instructions in `practice/fixtures/instructions.json` (there are also a few new English messages in `frontend/src/common/locales/locale-en.cst.js` and `frontend/src/common/locales/blockly-messages.srv.js`). You can also do a quick check of English version at http://en.localhost:8000. See our wiki for details of localization: https://github.com/effa/flocs/wiki/I18n-and-l10n

**Comment by jirmauritz** [comment]
Fixed two minor typos in e6a06593b6a650a28e7f9d9b9bd3c2f967048d84. Waiting for Jarda's response to close it.

**Comment by jcechak** [comment]
Should you find any rewording of the instructions inappropriate, feel free to revert my changes or reopen this issue.
