### ISSUE TITLE
Frontend diagram

### ISSUE THREAD

**Issue by effa** [effa/flocs#16]
Draw a diagram (or more) of the frontend application (and upload to a documentation folder or to the wiki). You can try to use something from Swing or invent your own diagram type (but then it's necessary to explain the semantics of everything in the diagram). The aim is to make it simple for everybody to grasp how the frontend is structured, how the communication works etc.

**Comment by jcechak** [comment]
Three diagrams were created and two of them (those containing more information) has been placed on a new wiki page under the section "Documentation". If there is a need to have some other process(es) or structure(s) in form of a diagram, reopen the issue or crate a new one with the specific need.
