### ISSUE TITLE
New blocks

### ISSUE THREAD

**Issue by effa** [effa/flocs#26]

**Comment by effa** [comment]
Blocks needed:
* for_loop_fixed (for _ in range(n): ...)
* for_loop_ - (for var in range(min, max): ...)
* variables (get, set)
* numbers and expressions (+ - * /  == < >)
* logic expressions (and, or, not)
* while_loop

**Comment by jcechak** [comment]
Document all available blocks and categories in separate wiki.

**Comment by jcechak** [comment]
define categories as constant and inject is into toolbox service
