### ISSUE TITLE
Baseline recommendation

### ISSUE THREAD

**Issue by jirmauritz** [effa/flocs#30]
Create more recommender models (B1, B2) - recommending for signed user.
Details in the picture below (later).

**Comment by effa** [comment]
![baselines](https://cloud.githubusercontent.com/assets/4967863/10589808/92c1f1fe-76ad-11e5-9e0e-a7719857aee8.JPG)

Correction: The suggeted baseline B2 is close to PFA ([Performance Factors Analysis](http://pact.cs.cmu.edu/koedinger/pubs/AIED%202009%20final%20Pavlik%20Cen%20Keodinger%20corrected.pdf)), not BKT.

And read relevant articles. You can use Google Scholar, but there is also a lot of useful links in our laboratory GD directory. For publications from our group see http://www.fi.muni.cz/adaptivelearning/?a=publications.
