### ISSUE TITLE
Problem with highlighting WhileUntil block

### ISSUE THREAD

**Issue by jirmauritz** [effa/flocs#31]
When you try to run WhileUntil cycle, the process stops and even reset does not work.  
Throws Unknown identifier: h:
```
highlightBlock('25');
while (h) {
  highlightBlock('27');
  moveForward();  highlightBlock('25');
}
```
You can try this in task-preview when you choose task with id 13 and try to solve it.

It is hard to create tasks without the preview, so please give the priority to this issue.

**Comment by jcechak** [comment]
The problem was that by default while/repeat blocks did not expect a JS code (function calls) as conditions. It expected boolean values. Bug was solved by redefining standard behaviour. This issue affected while/repeat loop and all if conditons as well. Both blocks are now working as expected.
