### ISSUE TITLE
Maximal number of blocks

### ISSUE THREAD

**Issue by jirmauritz** [effa/flocs#33]
Restrict maximal number of used blocks for specific task. Create new record in task model, which indicates max number of block for each task.
You can find blockly settings for this when injecting Blockly on the page (Blockly.inject()).
Visualisation of remaining blocks in the workspace.

Then, please, add number of blocks to every task in the task fixture.

**Comment by effa** [comment]
Done. See [Tasks wiki page](https://github.com/effa/flocs/wiki/Tasks) for how to set the limit in new tasks.
