### ISSUE TITLE
Tasks-concepts and user-concepts matrices

### ISSUE THREAD

**Issue by effa** [effa/flocs#46]
- concepts: programming, conditions, loops, logic expressions, colors, tokens, pits
- function for creating tasks-concepts matrix
- heuristic function for initial estimation of a difficulty of a task
- function for a new user-concepts row

**Comment by jirmauritz** [comment]
Solved with commits 0ba5a5c2dc166281d4def476f0cdaa0eae6b0f95, 418beac0753aa539c07b50ee2fb0d2f881e43308 and 91f7188debe107f85689e8f49f3919bbf8880830
