### ISSUE TITLE
New tasks using pits (and colors and tokens)

### ISSUE THREAD

**Issue by effa** [effa/flocs#50]
+ logical expressions

**Comment by jirmauritz** [comment]
Done with commits 0c373c9c1951a75e00b6b31b898dcf6301015949, f5fb6a6967844aff853a122f8346cafea7756c48, 7fd7a565ee6350550098abeffa84932198df7f64 and 9b491a7153bab6fc519fb5e50ffcd8a4a4f4a6bf.
